// eBizCard Configuration
// Admin authentication credentials for QR code generation
// IMPORTANT: For production use, implement server-side authentication
// This client-side validation is for demonstration purposes only
//
// NOTE: When deployed via GitHub Actions, this file is automatically generated
// with credentials from GitHub repository secrets (ADMIN_AUTH_USER_NAME and ADMIN_AUTH_SECRET_KEY).
// The values below are default/fallback values for local development only.

const CONFIG = {
    // Admin username for accessing the QR code generator
    ADMIN_AUTH_USER_NAME: 'admin',
    
    // Admin password for accessing the QR code generator
    // IMPORTANT: Change this default password to a strong, unique password
    // In production, this should be hashed and validated server-side
    ADMIN_AUTH_SECRET_KEY: 'ChangeThisPassword!2024'
};
